version: 0.2  
phases:
  install:
    commands:
      - echo "Entering install..."
  build:
    commands:
      - echo "Zipping lambda functions..."
      - cd Lambda
      - zip -r cfn_lambda.zip index-photos.py
      - cd ..
  post_build:
    commands:
      - echo "Updating lambda function..."
      - aws lambda update-function-code --function-name cfn_lambda --zip-file fileb://Lambda/cfn_lambda.zip
      - echo "Updating done!"
artifacts:
  type: zip
  files:
    - lf_cf.yaml
